//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBScripter.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBScripter.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connectiong database . . ..
        /// </summary>
        internal static string Message_ConnectiongDatabase {
            get {
                return ResourceManager.GetString("Message_ConnectiongDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting Stored Procedures ....
        /// </summary>
        internal static string Message_ScriptingStoredProcedures {
            get {
                return ResourceManager.GetString("Message_ScriptingStoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting Tables ....
        /// </summary>
        internal static string Message_ScriptingTables {
            get {
                return ResourceManager.GetString("Message_ScriptingTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting User Defined Aggregates ....
        /// </summary>
        internal static string Message_ScriptingUserDefinedAggregates {
            get {
                return ResourceManager.GetString("Message_ScriptingUserDefinedAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting User Defined Functions ....
        /// </summary>
        internal static string Message_ScriptingUserDefinedFunctions {
            get {
                return ResourceManager.GetString("Message_ScriptingUserDefinedFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripting Views ....
        /// </summary>
        internal static string Message_ScriptingViews {
            get {
                return ResourceManager.GetString("Message_ScriptingViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Procedure.
        /// </summary>
        internal static string ObjectType_StoredProcedure {
            get {
                return ResourceManager.GetString("ObjectType_StoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string ObjectType_Table {
            get {
                return ResourceManager.GetString("ObjectType_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Aggreagate.
        /// </summary>
        internal static string ObjectType_UserDefinedAggregate {
            get {
                return ResourceManager.GetString("ObjectType_UserDefinedAggregate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined Function.
        /// </summary>
        internal static string ObjectType_UserDefinedFunction {
            get {
                return ResourceManager.GetString("ObjectType_UserDefinedFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ObjectType_View {
            get {
                return ResourceManager.GetString("ObjectType_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoredProcedures.
        /// </summary>
        internal static string SubfolderName_StoredProcedures {
            get {
                return ResourceManager.GetString("SubfolderName_StoredProcedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string SubfolderName_Tables {
            get {
                return ResourceManager.GetString("SubfolderName_Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedAggregates.
        /// </summary>
        internal static string SubfolderName_UserDefinedAggregates {
            get {
                return ResourceManager.GetString("SubfolderName_UserDefinedAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserDefinedFunctions.
        /// </summary>
        internal static string SubfolderName_UserDefinedFunctions {
            get {
                return ResourceManager.GetString("SubfolderName_UserDefinedFunctions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string SubfolderName_Views {
            get {
                return ResourceManager.GetString("SubfolderName_Views", resourceCulture);
            }
        }
    }
}
